### ISSUE TITLE
Blacklisted call is still ringing for some seconds

### ISSUE THREAD

**Issue by naoliv** [kaliturin/BlackList#20]
I was noticing that while I receive a call from a blacklisted number, the phone still rings/vibrates for some seconds (maybe 1 or 2 seconds), before getting rejected.

Isn't it possible to directly and silently reject the call, without ringing/vibrating for some seconds?

**Comment by lynxlynx** [comment]
Me too. +1. Not very annoying, but sometimes this makes me think I have an important call.

**Comment by azakosath** [comment]
Just to add a logcat to the previous comments and to say that the call pass through without being rejected at all, but still the app sends notification about the call was blocked as  in #12.

`01-22 12:25:56.565 W/BroadcastQueue(1953): Permission Denial: receiving Intent { act=android.intent.action.PHONE_STATE flg=0x1000010 (has extras) } to com.kaliturin.blacklist/.receivers.CallBroadcastReceiver requires android.permission.READ_PRIVILEGED_PHONE_STATE due to sender android (uid 1000)
`
Device Xiaomi Mi A2 (crDroid v5.0 android 9.0)

**Comment by dhazel** [comment]
Happening for me too.

Google Pixel 2, Android 9

**Comment by puppykickr** [comment]
Yeah, me too.
Not very often.
Usually it stops in the middle of the first ring.

Not very annoying, and I am still very thankful for this app.

**Comment by nerdeirodasilva** [comment]
It's happening to me too, I'm using a custom ROM based on LineageOS (Android 9). Looking in the logcat, I found this error:

```
9-11 13:21:25.007  8289  8289 I bt_stack: [INFO:avrcp_service.cc(342)] virtual void bluetooth::avrcp::AvrcpService::SendMediaUpdate(bool, bool, bool) track
09-11 13:21:25.010  2085 15444 I PhoneInterfaceManager: endCall: called without modify phone state.
09-11 13:21:25.011  6621  6621 W System.err: java.lang.SecurityException: MODIFY_PHONE_STATE permission required.
09-11 13:21:25.011  6621  6621 W System.err:    at android.os.Parcel.createException(Parcel.java:1950)
09-11 13:21:25.011  6621  6621 W System.err:    at android.os.Parcel.readException(Parcel.java:1918)
09-11 13:21:25.011  6621  6621 W System.err:    at android.os.Parcel.readException(Parcel.java:1868)
09-11 13:21:25.011  6621  6621 W System.err:    at com.android.internal.telephony.ITelephony$Stub$Proxy.endCall(ITelephony.java:2277)
09-11 13:21:25.011  6621  6621 W System.err:    at com.kaliturin.blacklist.receivers.CallBroadcastReceiver.breakCall(CallBroadcastReceiver.java:157)
09-11 13:21:25.011  6621  6621 W System.err:    at com.kaliturin.blacklist.receivers.CallBroadcastReceiver.breakCallAndNotify(CallBroadcastReceiver.java:183
09-11 13:21:25.011  6621  6621 W System.err:    at com.kaliturin.blacklist.receivers.CallBroadcastReceiver.onReceive(CallBroadcastReceiver.java:139)
09-11 13:21:25.011  6621  6621 W System.err:    at android.app.ActivityThread.handleReceiver(ActivityThread.java:3418)
09-11 13:21:25.011  6621  6621 W System.err:    at android.app.ActivityThread.access$1200(ActivityThread.java:201)
09-11 13:21:25.011  6621  6621 W System.err:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1668)
09-11 13:21:25.011  6621  6621 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:106)
09-11 13:21:25.011  6621  6621 W System.err:    at android.os.Looper.loop(Looper.java:193)
09-11 13:21:25.011  6621  6621 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6724)
09-11 13:21:25.011  6621  6621 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
09-11 13:21:25.012  6621  6621 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
09-11 13:21:25.012  6621  6621 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
09-11 13:21:25.022  1355  2084 D ActivityManager: checkComponentPermission() adjusting {pid,uid} to {643,1013}
```

I even tried making it a system app with Titanium Backup, no luck. The phone still rings.
